name: Healing Through Nutrition
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78a40f'
    - '#ccecab'
    - '#aed942'
    - '#887b6b'
    - '#354b00'
  brandStrength: 0.1562979887239635
  lightness: 0.02670994307845831
  saturation: 0.4959477065131068
  rhythmicContrast: 0.8264929954893887
purpose: []
