name: Healing Through Nutrition
favicon: null
layout_spectrum: 0.994520915672183
typography_spectrum: 0.05036384938284755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1562979887239635
  lightness: 0.02670994307845831
  saturation: 0.4959477065131068
  rhythmicContrast: 0.8264929954893887
purpose: []
